CREATE TABLE `click_report` (
    `Id` INT(11) NOT NULL AUTO_INCREMENT,
    `AccountDescriptiveName` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdFormat` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdGroupId` BIGINT(20) NULL DEFAULT '0',
    `AdGroupName` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdGroupStatus` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdNetworkType1` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdNetworkType2` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AdVariationControlTrialArmId` BIGINT(20) NULL DEFAULT '0',
    `AdVariationTreatmentTrialArmId` BIGINT(20) NULL DEFAULT '0',
    `AdVariationTrialId` BIGINT(20) NULL DEFAULT '0',
    `AoiCityCriteriaId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AoiCountryCriteriaId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AoiMetroCriteriaId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AoiMostSpecificTargetId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `AoiRegionCriteriaId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `CampaignId` BIGINT(20) NULL DEFAULT '0',
    `CampaignLocationTargetId` BIGINT(20) NULL DEFAULT '0',
    `CampaignName` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `CampaignStatus` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `Clicks` INT(11) NULL DEFAULT NULL,
    `ClickType` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `CreativeId` BIGINT(20) NULL DEFAULT '0',
    `CriteriaId` BIGINT(20) NULL DEFAULT '0',
    `CriteriaParameters` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `Date` DATETIME NULL DEFAULT NULL,
    `Device` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `ExternalCustomerId` BIGINT(20) NULL DEFAULT '0',
    `GclId` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `KeywordMatchType` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `LopCityCriteriaId` BIGINT(20) NULL DEFAULT '0',
    `LopCountryCriteriaId` BIGINT(20) NULL DEFAULT '0',
    `LopMetroCriteriaId` BIGINT(20) NULL DEFAULT '0',
    `LopMostSpecificTargetId` BIGINT(20) NULL DEFAULT '0',
    `LopRegionCriteriaId` BIGINT(20) NULL DEFAULT '0',
    `MonthOfYear` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `Page` INT(11) NULL DEFAULT NULL,
    `Slot` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
    `UserListId` BIGINT(20) NULL DEFAULT '0',
    `Timestamp` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`Id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;